version: "3.8"
services:
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - ./data/db:/var/lib/mysql:rw
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: wp
      MARIADB_USER: wp
      MARIADB_PASSWORD: password
      MARIADB_AUTO_UPGRADE: 1
  wordpress:
    depends_on:
      - db
    build:
      context: ./wordpress/
    volumes:
      - ./html:/var/www/html:rw
      - ./data/logs:/var/www/logs:rw
    ports:
      - "8080:80"
    expose:
      - "80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DEBUG: 1
      WORDPRESS_TABLE_PREFIX: dwp_
      WORDPRESS_CONFIG_EXTRA: |
        /* debugging */
        define( 'WP_DEBUG_LOG', '/var/www/logs/wp-debug.log' );
        define( 'WP_MEMORY_LIMIT', '64M' );
        define( 'WP_MAX_MEMORY_LIMIT', '128M' );
        define( 'WP_HOME', 'http://localhost:8080' );
        define( 'WP_SITEURL', 'http://localhost:8080' );
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: wp
      PMA_PASSWORD: password
